function spm_RLT
% Rodent Longitudinal Toolbox wrapper to call RLT functions
%_______________________________________________________________________
% $Id: spm_RLT.m 103 2016-09-22 14:10:38Z gaser $

rev = '$Rev: 103 $';

% check that CAT12 toolbox is installed
if ~exist('cat_vol_groupwise_ls.m','file')
  error('Please install CAT12 toolbox from: http://www.neuro.uni-jena.de/cat12/cat12_latest.zip');
end

SPMid = spm('FnBanner',mfilename,rev);
[Finter,Fgraph,CmdLine] = spm('FnUIsetup','Rodent Longitudinal Toolbox');
spm_help('!Disp','RLT.man','',Fgraph,'Rodent Longitudinal Toolbox for SPM12');

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
	'Label',	'RLT',...
	'Separator',	'on',...
	'Tag',		'RLT',...
	'HandleVisibility','on');
h1  = uimenu(h0,...
	'Label',	'Mouse Data',...
	'Separator',	'off',...
	'Tag',		'Mouse Data',...
	'HandleVisibility','on');
h11  = uimenu(h1,...
	'Label',	'Initially reorient',...
	'Separator',	'off',...
	'Tag',		'Initially reorient data',...
	'CallBack','rlt_reorient_mouse;',...
	'HandleVisibility','on');
h12  = uimenu(h1,...
	'Label',	'Correct origin and voxel size',...
	'Separator',	'off',...
	'Tag',		'Correct origin (AC) and scale voxel size',...
	'CallBack','rlt_set_com_and_scale_mouse;',...
	'HandleVisibility','on');
h2  = uimenu(h0,...
	'Label',	'Rat Data',...
	'Separator',	'off',...
	'Tag',		'Rat Data',...
	'HandleVisibility','on');
h21  = uimenu(h2,...
	'Label',	'Initially reorient',...
	'Separator',	'off',...
	'Tag',		'Initially reorient data',...
	'CallBack','rlt_reorient_rat;',...
	'HandleVisibility','on');
h22  = uimenu(h2,...
	'Label',	'Correct origin and voxel size',...
	'Separator',	'off',...
	'Tag',		'Correct origin (AC) and scale voxel size',...
	'CallBack','rlt_set_com_and_scale_rat;',...
	'HandleVisibility','on');
h3  = uimenu(h0,...
	'Label',	'Preprocess longitudinal data',...
	'Separator',	'off',...
	'Tag',		'Preprocess longitudinal data',...
	'CallBack','spm_jobman(''interactive'','''',''matlabbatch.spm.tools.long_rodent'');',...
	'HandleVisibility','on');
h4  = uimenu(h0,...
	'Label',	'Check for updates',...
	'Separator',	'off',...
	'Tag',		'Check for updates',...
	'CallBack','rlt_update(1);',...
	'HandleVisibility','on');
